apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: 055665308353.dkr.ecr.us-west-2.amazonaws.com/order-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  selector:
    app: orderservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
