name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub (or another container registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker images
    - name: Build and push UserService Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/userservice:latest -f UserService/Dockerfile ./UserService
        docker push ${{ secrets.DOCKER_USERNAME }}/userservice:latest

    - name: Build and push OrderService Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/orderservice:latest -f OrderService/Dockerfile ./OrderService
        docker push ${{ secrets.DOCKER_USERNAME }}/orderservice:latest

    # Step 4: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 5: Authenticate to the Kubernetes cluster
    - name: Authenticate with Kubernetes cluster
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Test Kubernetes connection
      run: kubectl get namespaces
          

    # Step 6: Deploy to Kubernetes
    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f kubernetes-manifests/userservice-deployment.yaml
        kubectl apply -f kubernetes-manifests/orderservice-deployment.yaml
